### PR TITLE
fixed text out of button with ellipsis

### PR DESCRIPTION
**Pull request by Dito07**

### CODE REVIEW

**Comment by hachiojidev** [comment]
@Dito07 Thanks for addressing this. However I had the same concern and brought it up with the designer and he told me this is intentional. For example the button below is intended behavior:

image

**Comment by Dito07** [comment]
> @Dito07 Thanks for addressing this. However I had the same concern and brought it up with the designer and he told me this is intentional. For example the button below is intended behavior:
> 
> image
> 
> One more note: Please adhere to the commit linting. For example instead of `--fix--` it could be `fix: Button text wrap`
> 
> I think we can close this for now.

ALl right, but we have some cases like this:
littlebug

Hope it could help.

**Comment by hachiojidev** [comment]
@Dito07 You raise a good point.

With regards to the example you listed - I don't think buttons should ever have that much text. It would probably be better to use a tooltip or have the explanation text under it.

Let me look into it and get back to you.

**Comment by hachiojidev** [comment]
@Dito07 I had a chat with our designer and we both agreed it will better to redesign the voting block. Thank you for bringing this issue up. I will close this for now.

**Pull request closed without merging**
